export default function(){
  return[
    { option: 'Personal Information', id:1},
    { option: 'Basic Information', id:2 },
    { option: 'Description', id:3},
    { option: 'Location', id:4},
    { option: 'Amenities', id:5},
    { option: 'Gallery', id:6}
  ]
}

// Application State - Generated by reducers

// {
//   books: [{ title:'Harry Potter'},{ title: 'Javascript'}],
//   activeBook: { title: 'Javascript' }
// }

// books: booksReducer gives the same mapping as above books object a key of books with value .